title: ROHub portal documentation
description: ROHub is the reference research object management platform, allowing to manage and preserve your research work, make it available and discover new knowledge. As part of RELIANCE project ROHub has been onboarded and integrated in the European Open Science Cloud as a service for research management
theme: jekyll-theme-minimal
email: support@rohub.org
logo: images/image58.png
